### ISSUE TITLE
Tutorial typo in laser_propagation_2d.py

### ISSUE THREAD

**Issue by kcharbo3** [SmileiPIC/tutorials#10]
Hello, I believe `sqt` should be changed to `sqrt`.

https://github.com/SmileiPIC/tutorials/blob/147438ccc134485b66e750bc0558e7ee78a6dcf1/_extra/laser_propagation_2d.py#L12

**Comment by iltommi** [comment]
This is done on purpose and is part of the tutorial: find out the typo in the namelist.

https://smileipic.github.io/tutorials/basics_laser_vacuum.html#checking-your-input-file-in-test-mode

**Comment by mccoys** [comment]
Well done @kcharbo3 you found the bug 👍

**Comment by kcharbo3** [comment]
Oh my bad :joy: thanks for the quick reply
