### ISSUE TITLE
Units in thermal plasma tutorial

### ISSUE THREAD

**Issue by ottcsconsult** [SmileiPIC/tutorials#7]
Thanks for providing the really helpful tutorials! I'm new to PIC and am trying to wrap my head around Smilei's units.

In the <code>thermal_plasma_1d.py</code> example, the following choices are made:
```
ne = 1.                    # electron density (code units => reference density)
Ld = 1./64.                # Debye length (in code units => i.e. in skin-depth as ne=1)

Te = ne*Ld**2              # Te normalised in mec^2 (code units)
vth = math.sqrt(Te)
```
From reading the Smilei paper, ne = 1 being the reference density means that the reference frequency is the electron plasma frequency. I also understand that c = e = m_e = 1. Setting the Debye length fixes the temperature at given ne, but from the definition of the Debye length there appears to be an epsilon_0 missing when setting Te -- where did it go? Is it somehow absorbed in the unit conversion to m_e c^2? How?

A couple of unit conversion examples for novices would be greatly appreciated!

**Comment by mccoys** [comment]
Recall that both the density and the debye length are normalised. In `Te = ne*Ld**2` you can replace all three quantities by their non normalised version to recover the classical formula (with epsilon0). More precisely, replace Te by Te/(m_e c^2), replace ne by ne/(epsilon_0 m_e omega_r^2 /e^2), and replace Ld by Ld/(c/omega_r).

**Comment by ottcsconsult** [comment]
Thanks! This is very helpful!
