### ISSUE TITLE
"sqt" not found

### ISSUE THREAD

**Issue by PhilipDeegan** [SmileiPIC/tutorials#8]
https://github.com/SmileiPIC/tutorials/blob/master/_extra/laser_propagation_2d.py#L12

possibly typo of "sqrt"?

**Comment by MickaelGrech** [comment]
Hi!

Indeed, there is a typo here.
But it is here on purpose! to show that it's always nice to run "smilei_test" on your input file to find out if there is indeed some annoying typo before you submit your simulation on a cluster!

Keep SMILEIng!
